# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb6ae7bbe8f1e511f0c693a38b879ea47aae78e756cf931dc35ad991c5c4629204995a3905d18529e8f6279613fbc04c536f216c72d9d57de1fc303fcfb324f

test:
  secret_key_base: 440e2316ca902828ccc8a3ccb84d7d23d3828577a0456df9748083050f67a65a75ac36d7c0e473b35d6427ea709544a93ddf18a6e033a72b6f0168940b4ca1e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
